### PR TITLE
the second part of V0

### PR DESCRIPTION
**Pull request by chahid-rahouti**
How to find them

### CODE REVIEW

**Review by Blessed-joseph — CHANGES_REQUESTED** [review]
Chahid why did you use the terms first part and second part to define the approches, you can just name it first Method ans second method to resolve the problems .
and also try if it possible to add those file in gitignore
@chahid-rahouti

**Review by Blessed-joseph — APPROVED** [review]
Ok, i see

**Comment by Blessed-joseph** [comment]
Chahid did you add thos files generated by Latex to gitignore

**Review by Blessed-joseph — APPROVED** [review]

**Comment by chahid-rahouti** [comment]
Now, you can to look them

**Pull request merged**
